apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcp-demo-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
        - name: aspnetapp
          image: gcr.io/central-oath-228105/aspnetapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-demo-svc
  labels:
    app: aspnetapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: gcp-http-port
  selector:
    app: aspnetapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcp-demo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: gcp-demo-svc
              servicePort: gcp-http-port
